// Code generated by "go-enum-codegen -type MyEnum -stringer"; DO NOT EDIT.

package myenum

import (
	"database/sql/driver"
	"fmt"
)

// Scan implements sql.Scanner for MyEnum
func (e *MyEnum) Scan(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("failed to scan MyEnum value: expected type `string`, got `%T`", value)
	}
	switch str {
	case MyEnumOne.String():
		*e = MyEnumOne
	case MyEnumTwo.String():
		*e = MyEnumTwo
	case MyEnumThree.String():
		*e = MyEnumThree
	default:
		*e = MyEnumZero
	}

	return nil
}

// Value implements driver.Valuer for MyEnum
func (e MyEnum) Value() (driver.Value, error) {
	return e.String(), nil
}

// UnmarshalJSON implements json.Unmarshaler for MyEnum
func (e *MyEnum) UnmarshalJSON(data []byte) error {
	str := string(data)
	switch str {
	case MyEnumOne.String():
		*e = MyEnumOne
	case MyEnumTwo.String():
		*e = MyEnumTwo
	case MyEnumThree.String():
		*e = MyEnumThree
	default:
		*e = MyEnumZero
	}

	return nil
}

// MarshalJSON implements json.Marshaler for MyEnum
func (e MyEnum) MarshalJSON() ([]byte, error) {
	return []byte(e.String()), nil
}
